### ISSUE TITLE
Status not showing correctly for skype

### ISSUE THREAD

**Issue by kabili207** [SpectrumIM/spectrum2#266] opened 2018-01-25 15:42 UTC
It would appear that the idle status information is not being passed through from libpurple's skypeweb protocol to spectrum2. When I add the transport and the skypeweb plugin as accounts in pidgin, you can see that the spectrum2 account is not showing as idle when it should be.

![screenshot_2018-01-25_10-32-29](https://user-images.githubusercontent.com/1270500/35396933-17506676-01bc-11e8-8203-c0ef256739dc.png)

The mood information also appears to be missing, but it looks like there's already another open issue (#200) for that problem.

**Comment by Zombie-Ryushu** [comment] 2020-01-27 23:55
I can confirm this. It happens with the discord plugin too.

**Comment by vitalyster** [comment] 2021-12-25 23:23
Duplicate of #200

**Closed by vitalyster** 2021-12-25 23:23 UTC
