### ISSUE TITLE
purple-gowhatsapp compatibility

### ISSUE THREAD

**Issue by Nunction** [SpectrumIM/spectrum2#400] opened 2020-12-24 11:06 UTC
I am trying to get [purple-gowhatsapp](https://github.com/hoehermann/purple-gowhatsapp) running with Spectrum2. Linking `purple-gowhatsapp` with WhatsApp Web and subsequent sending and receiving of messages is working. However after completing the linking to WhatsApp Web and having Spectrum2 restart, the linking with WhatsApp Web is lost. This appears to happen because Spectrum2 recreates the `accounts.xml` on transport restart and `purple-gowhatsapp` persists the WhatsApp Web session in said file.

## Expected Behavior

WhatsApp Web linking (session) is preserved across reboots.

## Current Behavior

WhatsApp Web linking (session) is lost during restart.

## Possible Solution

Persist and restore `purple-gowhatsapp` specific session entries from `accounts.xml` in the database, similar to `prpl-steam-mobile` and `prpl-eionrobb-discord`.

Entry names as taken from `purple-gowhatsapp` [source](https://github.com/hoehermann/purple-gowhatsapp/blob/master/constants.h):

- int: `last-new-messages-timestamp`
- string: `clientid`
- string: `clientToken`
- string: `serverToken`
- string: `encKey`
- string: `macKey`
- string: `wid`

## Steps to Reproduce

1. Configure `purple-gowhatsapp` as transport in scpectrum.
2. Perform registration on transport
3. Restart Spectrum2
4. `accounts.xml` is recreated thus reasing `purple-gowhatsapp` specific entries.

## Environment

System: `Debian GNU/Linux 10 (buster)`  
APT repository: `deb https://packages.spectrum.im/spectrum2/ buster main`  
Spectrum2 version: `2.0.13`  
Transport config:
~~~ properties
[service]
frontend=xmpp
allowed_servers=example.com
jid = whatsapp.example.com
password = <password>
server = 127.0.0.1
port = 5347
backend_host = 127.0.0.1
web_directory=/var/www/spectrum/whatsapp/
web_url=https://example.com/spectrum/whatsapp
users_per_backend=10
backend=/usr/bin/spectrum2_libpurple_backend
protocol=prpl-hehoe-gowhatsapp

[identity]
name=Gateway to WhatsApp
type=whatsapp
category=gateway

[logging]
config = /etc/spectrum2/logging.cfg
backend_config = /etc/spectrum2/backend-logging.cfg

[database]
type = mysql
database = spectrum
server = 127.0.0.1
port = 3306
user = <user>
password = <password>
prefix = whatsapp_

[registration]
enable_public_registration = 0
username_label= You can enter an arbitrary username. However, it is recommended to use your own internationalized number. (e.g. 49123456789):

[purple]
# Use stored credentials for login.
# Default: true
restore-session = true

# Fetch contact list from phone on connect.
# Default: true
pull-contacts = false

# Mark displayed messages as read.
# Default: true
mark-read = true

# Download user profile pictures (may cause GUI hiccups after connecting)
# Default: false
get-icons = true

# Plain text login.
# Default: false
# Gajim sometimes has problems with inline images from this transport. May need to use plain text login and manually convert to a QR code image.
plain-text-login = false

# Display all contacts as online.
# Default: true
fake-online = true

# Number of received messages to remember as already shown.
# Default: 1000
message-id-store-size = 1000

# Do not show messages older than previous session.
# Default: false
message-timestamp-filter = true

# Treat system messages like normal messages (spectrum2 compatibility).
# Default: false
system-messages-are-ordinary-messages = true

# Download files from media (image, audio, video, document) messages.
# Default: false
download-attachments = true

# Try to download once only.
# Default: true
download-try-only-once = false

# Display images in conversation window after download
# Default: true
inline-images = true
~~~

**Comment by vitalyster** [comment] 2020-12-24 12:49
Yes, that is known issue, there is an ongoing PR to save/restore all settings from accounts.xml, but it was no complete yet.
Alternative solution - do not delete accounts.xml and keep all lib purple accounts there, need a lot of testing and this may have a lot of issues. Contributions are welcomed :)

**Comment by vitalyster** [comment] 2021-12-25 23:43
Duplicate of #264

**Closed by vitalyster** 2021-12-25 23:43 UTC
Labels: Feature
