### ISSUE TITLE
[purple] not working with prpl-flist

### ISSUE THREAD

**Issue by TomTheDragon** [SpectrumIM/spectrum2#274] opened 2018-02-24 22:12 UTC
I tried to set up some custom settings for prpl-flist over [purple] but it just sends me an "Internal Server Error, please reconnect." and shows me this error in the console:

terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::bad_any_cast> >'
  what():  boost::bad_any_cast: failed conversion using boost::any_cast
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::bad_any_cast> >'
  what():  boost::bad_any_cast: failed conversion using boost::any_cast
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::bad_any_cast> >'
  what():  boost::bad_any_cast: failed conversion using boost::any_cast
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::bad_any_cast> >'
  what():  boost::bad_any_cast: failed conversion using boost::any_cast

prpl-flist works fine when not using anything under [purple] but remember that this was working fine before in Spectrum 2.0.2

**Comment by vitalyster** [comment] 2018-02-25 05:32
Duplicate of #239

**Closed by vitalyster** 2018-02-25 05:32 UTC
