### ISSUE TITLE
Cannot sign in with telegram accounts having two-factor auth activated.

### ISSUE THREAD

**Issue by tallero** [SpectrumIM/spectrum2#316] opened 2018-12-02 04:41 UTC
When two-factor auth is activated, `telegram-purple` needs 

    <setting name='password-two-factor' type='string'>PASSWORD</setting>

in `accounts.xml` to sign in. Actually the only way I found to do this is manually editing the file on the server so at the moment two-factor users can not register to the transport.

Possible solutions I thought of:
- add a form that picks the value of this field on the registration screen (would this be client indipendent? does it break transport standard?)
- add the capacity to edit accounts.xml for purple backend in `settingsadhoccommand.cpp`
- adding support for "purple request API", so that we can use normal `telegram-purple` solution.way of retrieving the password.
- adding an exception in telegram-purple for clients not supporting "purple request API" not only for request_code but also for two auth password.

**Comment by vitalyster** [comment] 2018-12-02 06:52
Spectrum is able to forward purple input requests, but currently it needs to be:
1) explicitly whitelisted by primary string or another parameter, see [examples](https://github.com/SpectrumIM/spectrum2/blob/master/backends/libpurple/main.cpp#L1645)
2) token should be [saved](https://github.com/SpectrumIM/spectrum2/blob/master/backends/libpurple/main.cpp#L2123) in spectrum database  on successful sign in
3) and [restored](https://github.com/SpectrumIM/spectrum2/blob/master/backends/libpurple/main.cpp#L419) on next login request when Spectrum recreates accounts.xml from its database.

**Comment by vitalyster** [comment] 2021-12-25 23:43
Duplicate of #264

**Closed by vitalyster** 2021-12-25 23:43 UTC
