### ISSUE TITLE
Facebook group chats are broken

### ISSUE THREAD

**Issue by truenicoco** [SpectrumIM/spectrum2#308] opened 2018-08-27 11:04 UTC
For a few days, Facebook group chats through spectrum2 have been appearing empty.

When a facebook buddy sends a message to the group chat, I receive it as if it was sent as a private message to me.

```
7899: 2018-08-27 12:59:06,013 INFO  backend: conv_write_im()
7899: 2018-08-27 12:59:06,013 INFO  backend: Received message body='Ça m’a eve thanks' xhtml='' name='1472094786205699' 639697895
7899: 2018-08-27 12:59:08,420 INFO  backend: conv_write_im()
7899: 2018-08-27 12:59:08,420 INFO  backend: Received message body='Marche' xhtml='' name='1472094786205699' 639697895
```

where 639697895 is my buddy's Facebook ID and 1472094786205699 the group chat ID.

When I send a message to the group chat, I also receive the message as a private message "from me to me", and this is what the log says:

```
7899: 2018-08-27 12:53:54,637 INFO  backend: nicoco@nicoco.fr: sending typing notify to 1655615697791000
7899: 2018-08-27 12:53:59,790 INFO  backend: Sending message to '1655615697791000'
7899: 2018-08-27 12:53:59,793 INFO  backend: conv_write_im()
7899: 2018-08-27 12:53:59,793 INFO  backend: Received message body='merci pour les vidz !' xhtml='' name='1655615697791000' nicocool84
```
where 1655615697791000 is the group chat ID and nicocool84 my Facebook nickname.

I tried in pidgin and the behaviour is OK there. There wasn't any update of spectrum2 or libpurple-facebook since the problem appeared so I guess something changed on the Facebook side and the issue is spectrum2 related.

**Comment by truenicoco** [comment] 2018-08-27 11:08
```
$ apt-cache policy purple-facebook
purple-facebook:
  Installed: 20180323~ef6ae47~9ff9acf9fa14~145
  Candidate: 20180323~ef6ae47~9ff9acf9fa14~145
  Version table:
 *** 20180323~ef6ae47~9ff9acf9fa14~145 500
        500 http://download.opensuse.org/repositories/home:/jgeboski/Debian_9.0 ./ Packages
        100 /var/lib/dpkg/status

$ apt-cache policy spectrum2
spectrum2:
  Installed: 1:2.0.7-1
  Candidate: 1:2.0.7-1
  Version table:
 *** 1:2.0.7-1 500
        500 http://packages.spectrum.im/spectrum2 stretch/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by truenicoco** [comment] 2018-10-25 08:30
FWIW, now it happens only one some groupchats, some other ones are working fine (except their their names being the name of my transport instead of their own names in Conversations, but this is minor compared to this issue).

**Comment by hooger** [comment] 2019-01-28 11:37
I can confirm that the issue is ongoing. I experienced it from november and the "now it works fine for some..." phase happened about 2 weeks ago, but said group chats are back to the problematic behaviour (messages arrive as one-on-one messages).

Setup:
Debian 9, up-to-date
Spectrum from repositore
FB plugin compiled from source, I can't say when was the last time (couple month ago)

Thank you in advance for taking a look at it!

**Comment by vitalyster** [comment] 2019-01-28 12:15
Please update fb plugin to 0.9.6 first

**Comment by hooger** [comment] 2019-01-28 12:52
I updated to current master with purple-facebook, but it didn't solved the problem unfortunately.

**Comment by vitalyster** [comment] 2020-07-13 10:12
Does it reproduced on latest version?

**Comment by truenicoco** [comment] 2020-07-13 10:17
I would love to be able to answer, unfortunately because of [this issue](https://github.com/dequis/purple-facebook/issues/474), I haven't been able to use spectrum2 with facebook for a while.

More precisely, I used to be able to use it for a few hours/days once in a while, but cannot even try anymore since this ultimately led to my facebook account being locked. I haven't been able to unlock it for a few weeks now, apparently due to some bug in Facebook account unlocking process.

**Comment by vitalyster** [comment] 2021-12-25 23:32
Duplicate of #173

**Closed by vitalyster** 2021-12-25 23:32 UTC
