### ISSUE TITLE
Spectrum2 should perform JID sanitizing and lowercasing

### ISSUE THREAD

**Issue by ValdikSS** [SpectrumIM/spectrum2#290] opened 2018-05-15 21:23 UTC
Psi+ and Conversations XMPP clients always use lowercase JIDs, which makes impossible to e.g. join group chats in Telegram using telegram-libpurple, when the room name is not all in lowercase.
The same applies for restricted XMPP JID characters like '&' (see https://tools.ietf.org/html/rfc6122#appendix-A)

Spectrum2 should operate only with lowercase JIDs and replace or escape restricted characters according to RFC.

**Comment by vitalyster** [comment] 2018-05-15 22:31
Duplicate of #175 ?

**Closed** 2018-05-15 22:42 UTC
